#!/opt/homebrew/bin/php
<?php declare(strict_types=1);

if(php_sapi_name() !== 'cli') {
    exit;
}

const el = PHP_EOL;

function reg_cmd(string $name): object {
    $cmd = new stdClass();
    $cmd->name = $name;

    return $cmd;
}

$cmds = [
    $install = reg_cmd('install'),
    $search = reg_cmd('search'),
    $version = reg_cmd('version'),
];

print_r($cmds);

if($argc == 1) {
    echo el . 'Available Commands' . el;
    foreach($cmds as $cmd) {
        echo ' ' . $cmd->name . el;
    }
    echo el;
}

if($argc > 1) {
    $command = $argv[1];
    echo $command.el;
}