#!/opt/homebrew/bin/php
<?php declare(strict_types=1);

if(php_sapi_name() !== 'cli') {
    exit;
}

const el = PHP_EOL;

require_once __DIR__ . '/commands/register.php';

if($argc == 1) {
    echo 'Available Commands'.el;
    foreach($cmds as $cmd) {
        echo $cmd->name . "\t\t" . $cmd->desc . el;
    }
}

if($argc > 1) {
    $command = $argv[1];

    if(in_array($command, $cmd_names)) {
        echo $command . ' is valid' . el;

        if($command == 'install' || $command == 'Install') {
            echo $install->exec.el;
        }
    }
    else {
        echo 'Command not found: ' . $command.el;
    }
}